# Generated by Django 5.2.8 on 2025-11-24 06:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='call_link',
            field=models.URLField(default='', verbose_name='Enlace de llamada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
    ]
