# Generated by Django 5.2.8 on 2025-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_call_link_curso_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='show_home',
            field=models.BooleanField(default=False, verbose_name='Mostrar en la home'),
        ),
    ]
