# Generated by Django 5.2.8 on 2025-11-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_show_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='toc',
            field=models.FileField(blank=True, null=True, upload_to='cursos/toc/', verbose_name='Temario'),
        ),
    ]
