# Generated by Django 5.2.8 on 2025-11-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_curso_toc'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='curso_image',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/images/', verbose_name='Imagen del curso'),
        ),
    ]
