# Generated by Django 5.2.8 on 2025-11-28 06:56

import thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_curso_curso_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_image',
            field=thumbnails.fields.ImageField(blank=True, null=True, upload_to='cursos/images/', verbose_name='Imagen del curso'),
        ),
    ]
