# Generated by Django 5.2.8 on 2025-11-28 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_curso_curso_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
