# Generated by Django 5.2.8 on 2025-12-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='¿Se ha contactado con esta persona?'),
        ),
    ]
